---
:dataminer_definition: production_run_allocated_setups
:actions:
- :url: "/production/product_setups/product_setups/$:product_setup_id$"
  :text: view product setup
  :icon: view-show
  :title: View
  :hide_if_null: product_setup_id
- :url: "/production/runs/product_resource_allocations/$:id$/preview_label"
  :text: Preview label
  :icon: photo
  :title: Peview label
  :popup: true
- :separator: true
- :url: "/list/production_run_allocated_setups_view/multi?key=copy&id=$:id$&production_run_id=$:production_run_id$"
  :text: Copy this allocation
  :icon: copy
  :title: Copy this allocation
  :hide_if_null: product_setup_id
  :popup: true
:conditions:
  :standard:
    - :col: r.id
      :op: =
      :val: $:production_run_id$
:edit_rules:
  :url: /production/runs/production_runs/inline_edit_alloc/$:id$
  :editable_fields:
    product_setup_code:
      :editor: :select
      :width: 600
      :value_sql: SELECT fn_product_setup_code(id) FROM product_setups WHERE product_setup_template_id = (SELECT product_setup_template_id FROM production_runs WHERE id = $:production_run_id$)
    label_template_name:
      :editor: :select
      :width: 300
      :value_sql: SELECT label_template_name, id FROM label_templates WHERE application = 'Carton'
