---
:dataminer_definition: production_runs
:actions:
- :url: "/production/runs/production_runs/$:id$"
  :text: view
  :icon: view-show
  :title: View
  :popup: true
- :url: "/production/runs/production_runs/$:id$/edit"
  :text: edit
  :icon: edit
  :title: Edit
  :popup: true
- :url: "/production/runs/production_runs/$:id$/complete_setup"
  :text: Mark setup as complete
  :icon: toggle-on
  :title: Mark setup as complete
  :popup: true
  :hide_if_true: setup_complete
- :url: "/production/runs/production_runs/$:id$/select_template"
  :text: select product setup template
  :icon: arrow-left
  :title: Select Product Setup Template
  :popup: true
  :hide_if_true: setup_complete
- :url: "/production/runs/production_runs/$:id$/allocate_setups"
  :text: allocate product setups
  :icon: list
  :hide_if_null: product_setup_template_id
- :url: "/list/product_setups_on_runs/with_params?key=standard&production_run_id=$:id$"
  :text: view product setups
  :icon: list
  :title: Select Product Setup Template
  :hide_if_null: product_setup_template_id
- :url: "/production/runs/production_runs/$:id$"
  :text: delete
  :icon: delete
  :is_delete: true
  :popup: true
- :separator: true
- :url: "/development/statuses/list/production_runs/$:id$"
  :text: status
  :icon: information-solid
  :title: Status
  :popup: true
:page_controls:
- :control_type: :link
  :url: "/production/runs/production_runs/new"
  :text: New Production Run
  :style: :button
  :behaviour: :popup
