---
:dataminer_definition: production_run_allocated_target_customers
:conditions:
  :standard:
  - :col: r.id
    :op: "="
    :val: "$:production_run_id$"
:hide_for_client:
  hb:
  - system_code
  - fg_marks
  um:
  - system_code
  - fg_marks
  ud:
  - system_code
  - fg_marks
  sr:
  - system_code
  - fg_marks
  srp:
  - system_code
  - fg_marks
