---
:dataminer_definition: product_setup_details_on_runs
:captions:
  :conditions:
    :standard: Product Setup Details for run $:production_run_id$
:actions:
- :url: "/production/product_setups/product_setups/$:id$"
  :text: view
  :icon: view-show
  :title: View
- :url: "/production/runs/production_runs/$:production_run_id$/product_setup/$:id$/print_label"
  :text: Print carton label
  :icon: printer
  :title: Print carton label
  :popup: true
:conditions:
  :standard:
  - :col: production_runs.id
    :op: "="
    :val: "$:production_run_id$"
:hide_for_client:
  hb:
  - bom_code
  - fg_marks
  - gtin_code
  um:
  - bom_code
  - fg_marks
  - gtin_code
  ud:
  - bom_code
  - fg_marks
  - gtin_code
  sr:
  - bom_code
  - fg_marks
  - gtin_code
  srp:
  - bom_code
  - fg_marks
  - gtin_code
