---
:dataminer_definition: production_runs
:actions:
- :url: "/production/runs/production_runs/$:id$"
  :text: view
  :icon: view-show
  :title: View
  :popup: true
- :url: "/production/runs/production_runs/$:id$/edit"
  :text: edit
  :icon: edit
  :title: Edit
  :popup: true
- :url: "/production/runs/production_runs/$:id$"
  :text: delete
  :icon: delete
  :is_delete: true
  :popup: true
:page_controls:
- :control_type: :link
  :url: "/production/runs/production_runs/new"
  :text: New Production Run
  :style: :button
  :behaviour: :popup
