---
:caption: Product Setup Templates
:sql: SELECT product_setup_templates.id, product_setup_templates.template_name, product_setup_templates.description,
  product_setup_templates.cultivar_group_id, product_setup_templates.cultivar_id,
  product_setup_templates.packhouse_resource_id, product_setup_templates.production_line_id, product_setup_templates.season_group_id,
  product_setup_templates.season_id, product_setup_templates.active, product_setup_templates.created_at, product_setup_templates.updated_at,
  cultivar_groups.cultivar_group_code, cultivars.cultivar_name, plant_resources.plant_resource_code
  AS packhouse_resource_code, plant_resources2.plant_resource_code AS production_line_code,
  season_groups.season_group_code, seasons.season_code, fn_current_status('product_setup_templates',
  product_setup_templates.id) AS status, fn_product_setup_template_in_production(product_setup_templates.id)
  AS in_production, CASE WHEN fn_product_setup_template_in_production(product_setup_templates.id)
  THEN 'warning' WHEN NOT product_setup_templates.active THEN 'inactive' ELSE NULL
  END AS colour_rule FROM product_setup_templates JOIN cultivar_groups ON cultivar_groups.id
  = product_setup_templates.cultivar_group_id LEFT JOIN cultivars ON cultivars.id
  = product_setup_templates.cultivar_id LEFT JOIN plant_resources ON plant_resources.id
  = product_setup_templates.packhouse_resource_id LEFT JOIN plant_resources plant_resources2
  ON plant_resources2.id = product_setup_templates.production_line_id LEFT
  JOIN season_groups ON season_groups.id = product_setup_templates.season_group_id
  LEFT JOIN seasons ON seasons.id = product_setup_templates.season_id
:limit: 
:offset: 
:external_settings:
  :colour_key:
    warning: Active in run
    inactive: De-activated
:columns:
  id:
    :name: id
    :sequence_no: 12
    :caption: Id
    :namespaced_name: product_setup_templates.id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  template_name:
    :name: template_name
    :sequence_no: 1
    :caption: Template name
    :namespaced_name: product_setup_templates.template_name
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  description:
    :name: description
    :sequence_no: 2
    :caption: Description
    :namespaced_name: product_setup_templates.description
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  cultivar_group_id:
    :name: cultivar_group_id
    :sequence_no: 13
    :caption: Cultivar group
    :namespaced_name: product_setup_templates.cultivar_group_id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  cultivar_id:
    :name: cultivar_id
    :sequence_no: 14
    :caption: Cultivar
    :namespaced_name: product_setup_templates.cultivar_id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  packhouse_resource_id:
    :name: packhouse_resource_id
    :sequence_no: 15
    :caption: Packhouse resource
    :namespaced_name: product_setup_templates.packhouse_resource_id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  production_line_id:
    :name: production_line_id
    :sequence_no: 16
    :caption: Production line resource
    :namespaced_name: product_setup_templates.production_line_id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  season_group_id:
    :name: season_group_id
    :sequence_no: 17
    :caption: Season group
    :namespaced_name: product_setup_templates.season_group_id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  season_id:
    :name: season_id
    :sequence_no: 18
    :caption: Season
    :namespaced_name: product_setup_templates.season_id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  active:
    :name: active
    :sequence_no: 9
    :caption: Active
    :namespaced_name: product_setup_templates.active
    :data_type: :boolean
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  created_at:
    :name: created_at
    :sequence_no: 19
    :caption: Created at
    :namespaced_name: product_setup_templates.created_at
    :data_type: :datetime
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  updated_at:
    :name: updated_at
    :sequence_no: 20
    :caption: Updated at
    :namespaced_name: product_setup_templates.updated_at
    :data_type: :datetime
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  cultivar_group_code:
    :name: cultivar_group_code
    :sequence_no: 3
    :caption: Cultivar group code
    :namespaced_name: cultivar_groups.cultivar_group_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  cultivar_name:
    :name: cultivar_name
    :sequence_no: 4
    :caption: Cultivar name
    :namespaced_name: cultivars.cultivar_name
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  packhouse_resource_code:
    :name: packhouse_resource_code
    :sequence_no: 5
    :caption: Packhouse resource code
    :namespaced_name: plant_resources.plant_resource_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  production_line_code:
    :name: production_line_code
    :sequence_no: 6
    :caption: Production line resource code
    :namespaced_name: plant_resources2.plant_resource_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  season_group_code:
    :name: season_group_code
    :sequence_no: 7
    :caption: Season group code
    :namespaced_name: season_groups.season_group_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  season_code:
    :name: season_code
    :sequence_no: 8
    :caption: Season code
    :namespaced_name: seasons.season_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  status:
    :name: status
    :sequence_no: 11
    :caption: Status
    :namespaced_name: 
    :data_type: :string
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  in_production:
    :name: in_production
    :sequence_no: 10
    :caption: In production
    :namespaced_name: 
    :data_type: :boolean
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  colour_rule:
    :name: colour_rule
    :sequence_no: 21
    :caption: Colour rule
    :namespaced_name: 
    :data_type: :string
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
:query_parameter_definitions:
- :column: product_setups.product_setup_template_id
  :caption: Template name
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 1
  :list_def: SELECT template_name, id FROM product_setup_templates ORDER BY template_name
- :column: product_setup_templates.cultivar_group_id
  :caption: Cultivar group
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 2
  :list_def: SELECT cultivar_group_code, id FROM cultivar_groups ORDER BY cultivar_group_code
- :column: product_setup_templates.cultivar_id
  :caption: Cultivar
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 3
  :list_def: SELECT cultivar_name, id FROM cultivars ORDER BY cultivar_name
- :column: product_setup_templates.packhouse_resource_id
  :caption: Packhouse resource
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 4
  :list_def: SELECT plant_resources.plant_resource_code, plant_resources.id FROM plant_resources
    JOIN plant_resource_types ON plant_resource_types.id = plant_resources.plant_resource_type_id
    WHERE plant_resource_type_code = 'PACKHOUSE' ORDER BY plant_resource_code
- :column: product_setup_templates.production_line_id
  :caption: Production line resource
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 5
  :list_def: SELECT plant_resources.plant_resource_code, plant_resources.id FROM plant_resources
    JOIN plant_resource_types ON plant_resource_types.id = plant_resources.plant_resource_type_id
    WHERE plant_resource_type_code = 'LINE' ORDER BY plant_resource_code
- :column: product_setup_templates.season_group_id
  :caption: Season group
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 6
  :list_def: SELECT season_group_code, id FROM season_groups ORDER BY season_group_code
- :column: product_setup_templates.season_id
  :caption: Season
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 7
  :list_def: SELECT season_code, id FROM seasons ORDER BY season_code
- :column: product_setup_templates.active
  :caption: Active?
  :data_type: :boolean
  :control_type: :list
  :default_value:
  :ordered_list: false
  :ui_priority: 8
  :list_def: [true, false]
