---
:caption: Product Setup Details
:sql: SELECT product_setup_templates.template_name, fn_product_setup_code(product_setups.id) AS product_setup_code,
      fn_product_setup_in_production(product_setups.id) AS in_production, commodities.code AS commodity_code,
      marketing_varieties.marketing_variety_code, standard_pack_codes.standard_pack_code AS standard_pack,
      basic_pack_codes.basic_pack_code AS pack_code, std_fruit_size_counts.size_count_value AS size_count,
      fruit_actual_counts_for_packs.actual_count_for_pack AS actual_count, fruit_size_references.size_reference,
      organizations.short_description AS marketing_organization, target_market_groups.target_market_group_name, marks.mark_code,
      cust_mkt.marketing_variety_code AS cust_mkt_variety, inventory_codes.inventory_code,
      pallet_formats.description AS pallet_format_description, cartons_per_pallet.cartons_per_pallet,
      pm_boms.bom_code, product_setups.id,product_setups.product_setup_template_id, product_setups.extended_columns,
      product_setups.client_size_reference, product_setups.client_product_code, product_setups.marketing_order_number,
      product_setups.sell_by_code, product_setups.pallet_label_name, product_setups.active, product_setups.created_at, product_setups.updated_at,
      CASE WHEN fn_product_setup_in_production(product_setups.id) THEN 'warning'
      WHEN NOT product_setups.active THEN 'inactive' ELSE NULL END AS colour_rule,
      (SELECT array_agg(pst.treatment_code)
      FROM (SELECT t.treatment_code
      FROM treatments t
      JOIN product_setups ps ON t.id = ANY (ps.treatment_ids)
      WHERE ps.id = product_setups.id
      ORDER BY t.treatment_code DESC) AS pst) AS product_setup_treatments
      FROM product_setups
      JOIN product_setup_templates ON product_setup_templates.id = product_setups.product_setup_template_id
      JOIN marketing_varieties ON marketing_varieties.id = product_setups.marketing_variety_id
      LEFT JOIN std_fruit_size_counts ON std_fruit_size_counts.id = product_setups.std_fruit_size_count_id
      LEFT JOIN commodities ON commodities.id = std_fruit_size_counts.commodity_id
      JOIN basic_pack_codes ON basic_pack_codes.id = product_setups.basic_pack_code_id
      JOIN standard_pack_codes ON standard_pack_codes.id = product_setups.standard_pack_code_id LEFT
      JOIN fruit_actual_counts_for_packs ON fruit_actual_counts_for_packs.id = product_setups.fruit_actual_counts_for_pack_id
      LEFT JOIN fruit_size_references ON fruit_size_references.id = product_setups.fruit_size_reference_id
      JOIN party_roles ON party_roles.id = product_setups.marketing_org_party_role_id
      JOIN organizations ON organizations.id = party_roles.organization_id
      JOIN target_market_groups ON target_market_groups.id = product_setups.packed_tm_group_id
      JOIN marks ON marks.id = product_setups.mark_id
      LEFT JOIN customer_variety_varieties ON customer_variety_varieties.id = product_setups.customer_variety_variety_id
      LEFT JOIN marketing_varieties cust_mkt ON cust_mkt.id = customer_variety_varieties.marketing_variety_id
      LEFT JOIN inventory_codes ON inventory_codes.id = product_setups.inventory_code_id
      JOIN pallet_formats ON pallet_formats.id = product_setups.pallet_format_id
      JOIN cartons_per_pallet ON cartons_per_pallet.id = product_setups.cartons_per_pallet_id
      LEFT JOIN pm_boms ON pm_boms.id = product_setups.pm_bom_id
:limit: 
:offset: 
:external_settings:
  :render_url: 
  :colour_key:
    warning: Active on run
    inactive: De-activated
:columns:
  template_name:
    :name: template_name
    :sequence_no: 2
    :caption: Template name
    :namespaced_name: product_setup_templates.template_name
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  product_setup_code:
    :name: product_setup_code
    :sequence_no: 1
    :caption: Product setup code
    :namespaced_name: 
    :data_type: :string
    :width: 800
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  in_production:
    :name: in_production
    :sequence_no: 30
    :caption: In production
    :namespaced_name: in_production
    :data_type: :boolean
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  commodity_code:
    :name: commodity_code
    :sequence_no: 3
    :caption: Commodity code
    :namespaced_name: commodities.code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  marketing_variety_code:
    :name: marketing_variety_code
    :sequence_no: 4
    :caption: Marketing variety code
    :namespaced_name: marketing_varieties.marketing_variety_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  standard_pack:
    :name: standard_pack
    :sequence_no: 5
    :caption: Standard pack
    :namespaced_name: standard_pack_codes.standard_pack_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  pack_code:
    :name: pack_code
    :sequence_no: 6
    :caption: Pack code
    :namespaced_name: basic_pack_codes.basic_pack_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  size_count:
    :name: size_count
    :sequence_no: 7
    :caption: Size count
    :namespaced_name: std_fruit_size_counts.size_count_value
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  actual_count:
    :name: actual_count
    :sequence_no: 8
    :caption: Actual count
    :namespaced_name: fruit_actual_counts_for_packs.actual_count_for_pack
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  size_reference:
    :name: size_reference
    :sequence_no: 9
    :caption: Size reference
    :namespaced_name: fruit_size_references.size_reference
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  marketing_organization:
    :name: marketing_organization
    :sequence_no: 10
    :caption: Marketing organization
    :namespaced_name: organizations.short_description
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  target_market_group_name:
    :name: target_market_group_name
    :sequence_no: 11
    :caption: Target market group name
    :namespaced_name: target_market_groups.target_market_group_name
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  mark_code:
    :name: mark_code
    :sequence_no: 12
    :caption: Mark code
    :namespaced_name: marks.mark_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  cust_mkt_variety:
    :name: cust_mkt_variety
    :sequence_no: 13
    :caption: Cust mkt variety
    :namespaced_name: cust_mkt.marketing_variety_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  inventory_code:
    :name: inventory_code
    :sequence_no: 14
    :caption: Inventory code
    :namespaced_name: inventory_codes.inventory_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  pallet_format_description:
    :name: pallet_format_description
    :sequence_no: 15
    :caption: Pallet format description
    :namespaced_name: pallet_formats.description
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  cartons_per_pallet:
    :name: cartons_per_pallet
    :sequence_no: 16
    :caption: Cartons per pallet
    :namespaced_name: cartons_per_pallet.cartons_per_pallet
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  bom_code:
    :name: bom_code
    :sequence_no: 17
    :caption: Bom code
    :namespaced_name: pm_boms.bom_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  product_setup_treatments:
    :name: product_setup_treatments
    :sequence_no: 18
    :caption: Product setup treatments
    :namespaced_name: product_setup_treatments.product_setup_treatments
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  id:
    :name: id
    :sequence_no: 29
    :caption: Id
    :namespaced_name: product_setups.id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  product_setup_template_id:
    :name: product_setup_template_id
    :sequence_no: 19
    :caption: Product setup template
    :namespaced_name: product_setups.product_setup_template_id
    :data_type: :string
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  extended_columns:
    :name: extended_columns
    :sequence_no: 20
    :caption: Extended columns
    :namespaced_name: product_setups.extended_columns
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  client_size_reference:
    :name: client_size_reference
    :sequence_no: 21
    :caption: Client size reference
    :namespaced_name: product_setups.client_size_reference
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  client_product_code:
    :name: client_product_code
    :sequence_no: 22
    :caption: Client product code
    :namespaced_name: product_setups.client_product_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  marketing_order_number:
    :name: marketing_order_number
    :sequence_no: 23
    :caption: Marketing order number
    :namespaced_name: product_setups.marketing_order_number
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  sell_by_code:
    :name: sell_by_code
    :sequence_no: 24
    :caption: Sell by code
    :namespaced_name: product_setups.sell_by_code
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  pallet_label_name:
    :name: pallet_label_name
    :sequence_no: 25
    :caption: Pallet label name
    :namespaced_name: product_setups.pallet_label_name
    :data_type: :string
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  active:
    :name: active
    :sequence_no: 26
    :caption: Active
    :namespaced_name: product_setups.active
    :data_type: :boolean
    :width: 
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  created_at:
    :name: created_at
    :sequence_no: 27
    :caption: Created at
    :namespaced_name: product_setups.created_at
    :data_type: :datetime
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  updated_at:
    :name: updated_at
    :sequence_no: 28
    :caption: Updated at
    :namespaced_name: product_setups.updated_at
    :data_type: :datetime
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  colour_rule:
    :name: colour_rule
    :sequence_no: 31
    :caption: Colour rule
    :namespaced_name: 
    :data_type: :string
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
:query_parameter_definitions:
- :column: product_setups.product_setup_template_id
  :caption: Template name
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 1
  :list_def: SELECT template_name, id FROM product_setup_templates ORDER BY template_name
- :column: product_setup_templates.cultivar_group_id
  :caption: Cultivar group
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 2
  :list_def: SELECT cultivar_group_code, id FROM cultivar_groups ORDER BY cultivar_group_code
- :column: product_setup_templates.cultivar_id
  :caption: Cultivar
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 3
  :list_def: SELECT cultivar_name, id FROM cultivars ORDER BY cultivar_name
- :column: product_setup_templates.packhouse_resource_id
  :caption: Packhouse resource
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 4
  :list_def: SELECT plant_resources.plant_resource_code, plant_resources.id FROM plant_resources
    JOIN plant_resource_types ON plant_resource_types.id = plant_resources.plant_resource_type_id
    WHERE plant_resource_type_code = 'PACKHOUSE' ORDER BY plant_resource_code
- :column: product_setup_templates.production_line_resource_id
  :caption: Production line resource
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 5
  :list_def: SELECT plant_resources.plant_resource_code, plant_resources.id FROM plant_resources
    JOIN plant_resource_types ON plant_resource_types.id = plant_resources.plant_resource_type_id
    WHERE plant_resource_type_code = 'LINE' ORDER BY plant_resource_code
- :column: product_setup_templates.season_group_id
  :caption: Season group
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 6
  :list_def: SELECT season_group_code, id FROM season_groups ORDER BY season_group_code
- :column: product_setup_templates.season_id
  :caption: Season
  :data_type: :integer
  :control_type: :list
  :default_value: 
  :ordered_list: true
  :ui_priority: 7
  :list_def: SELECT season_code, id FROM seasons ORDER BY season_code
- :column: product_setups.active
  :caption: Active?
  :data_type: :boolean
  :control_type: :list
  :default_value:
  :ordered_list: false
  :ui_priority: 8
  :list_def: [true, false]
- :column: fn_product_setup_in_production(product_setups.id)
  :caption: in_production
  :data_type: :boolean
  :control_type: :list
  :default_value:
  :ordered_list: false
  :ui_priority: 9
  :list_def: [true, false]
